Repository sofastack/sofa-registry, pull requests merged in 2020-10, with the labels that each got.

#140 Clean log
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/change/event/DataChangeEventQueue.java
  server/server/data/src/main/resources/logback-spring.xml
  server/server/data/src/test/resources/logback-test.xml
  server/server/integration/src/main/resources/logback-spring.xml
  server/server/session/src/main/java/com/alipay/sofa/registry/server/session/scheduler/task/DataChangeFetchCloudTask.java
  server/server/session/src/main/resources/logback-spring.xml
Labels: First-time contributor, cla:yes, size/M

#141 Disconnect delay configurable
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/bootstrap/DataServerConfig.java
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/remoting/sessionserver/SessionServerConnectionFactory.java
  server/server/data/src/main/resources/application.properties
Labels: First-time contributor, cla:yes, size/S

#145 change renew expired duration to 15s
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/store/RenewDecorate.java
Labels: cla:yes, size/XS
