Repository sofastack/sofa-registry, pull requests merged in 2020-02, with the labels that each got.

#87 add case sensitive feature and unpub/unsub event
  server/common/model/src/main/java/com/alipay/sofa/registry/common/model/constants/ValueConstants.java
  server/common/model/src/main/java/com/alipay/sofa/registry/common/model/store/DataInfo.java
  server/common/util/src/main/java/com/alipay/sofa/registry/task/listener/TaskEvent.java
Labels: cla:yes

#88 reduce cache log
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/cache/CacheDigestTask.java
Labels: cla:yes, size/XS

#92 fix close push fail when case not sensitive
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/consistency/pom.xml
  server/distribution/data/pom.xml
  server/distribution/integration/pom.xml
  server/distribution/meta/pom.xml
  server/distribution/pom.xml
  server/distribution/session/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/remoting/handler/FetchProvideDataRequestHandler.java
  server/server/pom.xml
  server/server/session/pom.xml
  server/store/api/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: bug, cla:yes, size/M
