Repository sofastack/sofa-registry, pull requests merged in 2020-05, with the labels that each got.

#108 chore: update version to 5.4.3-SNAPSHOT
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/consistency/pom.xml
  server/distribution/data/pom.xml
  server/distribution/integration/pom.xml
  server/distribution/meta/pom.xml
  server/distribution/pom.xml
  server/distribution/session/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/pom.xml
  server/server/session/pom.xml
  server/store/api/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: cla:yes, size/M

#102 Fix windows package
  server/distribution/data/distribution-data.xml
  server/distribution/integration/distribution-integration.xml
  server/distribution/meta/distribution-meta.xml
  server/distribution/session/distribution-session.xml
Labels: bug, cla:yes, size/S

#100 update DataChangeEventQueue: add log for onChange
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/change/event/DataChangeEventQueue.java
Labels: cla:yes, size/XS
