Repository sofastack/sofa-registry, pull requests merged in 2021-12, with the labels that each got.

#166 Update README.md to suggest other developers to use Java JDK 8 rather than JDK 16
  README.md
Labels: cla:no, First-time contributor, size/XS

#182 add GitHub action
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  Makefile
  README.md
  VERSION
  codecov.yml
  pom.xml
  server/common/util/src/test/resources/log4j2.xml
  server/server/data/src/test/resources/log4j2.xml
  server/server/meta/src/test/java/com/alipay/sofa/registry/common/model/slot/BaseSlotFunctionTest.java
  server/server/meta/src/test/java/com/alipay/sofa/registry/server/meta/slot/chaos/SlotChaosTest.java
  server/server/meta/src/test/resources/log4j2.xml
  server/server/session/src/test/resources/log4j2.xml
  test/pom.xml
  test/src/main/resources/log4j2.xml
  test/src/test/java/com/alipay/sofa/registry/test/BaseIntegrationTest.java
  test/src/test/resources/application-integrate.properties
  test/src/test/resources/log4j2.xml
Labels: cla:yes, size/L

#183 Readme
  README.md
Labels: cla:yes, size/XS

#184 codecov
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  README.md
  pom.xml
  test/pom.xml
Labels: cla:yes, size/S

#185 update image repositry
  Makefile
  README.md
  docker/kube/sofa-registry/base-integration/integration.yaml
  docker/kube/sofa-registry/base-standalone/data.yaml
  docker/kube/sofa-registry/base-standalone/meta.yaml
  docker/kube/sofa-registry/base-standalone/session.yaml
  docker/kube/sofa-registry/overlays/integration-dc1/kustomization.yaml
  docker/kube/sofa-registry/overlays/standalone-dc2/kustomization.yaml
Labels: cla:yes, size/M
