Repository sofastack/sofa-registry, pull requests merged in 2022-06, with the labels that each got.

#227 修复RegistryCoreOpsResource关流量
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/impl/src/main/java/com/alipay/sofa/registry/client/provider/DirectServerManager.java
  client/impl/src/test/java/com/alipay/sofa/registry/client/provider/DirectServerManagerTest.java
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/distribution/all/pom.xml
  server/distribution/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/bootstrap/MetaServerConfiguration.java
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/resource/RegistryCoreOpsResource.java
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/resource/RegistryCoreOpsV2Resource.java
  server/server/meta/src/test/java/com/alipay/sofa/registry/server/meta/resource/RegistryCoreOpsResourceTest.java
  server/server/pom.xml
  server/server/session/pom.xml
  server/server/shared/pom.xml
  server/store/api/pom.xml
  server/store/jdbc/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: cla:yes, size/L

#228 fix unit test action
  .github/workflows/integration-test.yml
  .github/workflows/unit-test.yml
  client/impl/src/main/java/com/alipay/sofa/registry/client/provider/DirectServerManager.java
  client/impl/src/test/java/com/alipay/sofa/registry/client/provider/DirectServerManagerTest.java
  server/remoting/bolt/src/test/java/com/alipay/sofa/registry/remoting/bolt/BoltServerTest.java
Labels: bug, cla:yes, size/M

#241 add source analyze doc
  README.md
Labels: cla:yes, First-time contributor, size/XS
