Repository sofastack/sofa-registry, pull requests merged in 2022-07, with the labels that each got.

#242 add source analyze doc
  README.md
Labels: cla:no, First-time contributor, size/XS

#236 Add source analyze doc.
  README.md
Labels: cla:yes, First-time contributor, size/XS

#243 modify README.md
  README.md
Labels: cla:yes, First-time contributor, size/XS

#244 Dev source analyze
  README.md
Labels: cla:yes, First-time contributor, size/XS

#246 fix: graceful shutdown
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/distribution/all/pom.xml
  server/distribution/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/pom.xml
  server/server/session/pom.xml
  server/server/shared/pom.xml
  server/server/shared/src/main/java/com/alipay/sofa/registry/server/shared/meta/AbstractMetaServerService.java
  server/store/api/pom.xml
  server/store/api/src/main/java/com/alipay/sofa/registry/store/api/elector/AbstractLeaderElector.java
  server/store/jdbc/pom.xml
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/elector/MetaJdbcLeaderElector.java
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: bug, cla:yes, size/M

#238 Add source analyze doc.
  README.md
Labels: cla:yes, First-time contributor, size/XS

#248 fix mybatis
  pom.xml
Labels: bug, cla:yes, size/XS

#245 chore: bolt timeout to 45s
  README.md
  server/remoting/bolt/src/main/java/com/alipay/sofa/registry/remoting/bolt/exchange/BoltExchange.java
Labels: cla:yes, size/S
