Repository sofastack/sofa-registry, pull requests merged in 2022-08, with the labels that each got.

#256 Fix meta/session shutdown.sh bug
  server/distribution/all/bin/meta/shutdown.sh
  server/distribution/all/bin/session/shutdown.sh
Labels: bug, cla:yes, First-time contributor, size/XS

#255 Explicitly specify spring-boot-maven-plugin version
  pom.xml
Labels: cla:yes, First-time contributor, size/S

#253 metadata digest api
  server/server/session/src/main/java/com/alipay/sofa/registry/server/session/resource/SessionDigestResource.java
  server/store/api/src/main/java/com/alipay/sofa/registry/store/api/repository/AppRevisionRepository.java
  server/store/api/src/main/java/com/alipay/sofa/registry/store/api/repository/InterfaceAppsRepository.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/repository/impl/AppRevisionContainer.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/repository/impl/AppRevisionJdbcRepository.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/repository/impl/InterfaceAppsIndexContainer.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/repository/impl/InterfaceAppsJdbcRepository.java
  server/store/jraft/src/main/java/com/alipay/sofa/registry/jraft/repository/impl/AppRevisionRaftRepository.java
  server/store/jraft/src/main/java/com/alipay/sofa/registry/jraft/repository/impl/InterfaceAppsRaftRepository.java
Labels: cla:yes, size/M

#254 add tarLongFileMode=posix configuration for maven-assembly-plugin
  server/distribution/all/pom.xml
Labels: cla:yes, First-time contributor, size/XS

#258 fix metadata digest api
  server/server/session/src/main/java/com/alipay/sofa/registry/server/session/resource/SessionDigestResource.java
  server/store/api/src/main/java/com/alipay/sofa/registry/store/api/repository/InterfaceAppsRepository.java
  test/src/test/java/com/alipay/sofa/registry/test/resource/session/SessionDigestResourceTest.java
Labels: bug, cla:yes, size/L

#257 chore: migrate revision servie_param field to mediumtext
  VERSION
  create_table.sql
  server/common/model/src/main/java/com/alipay/sofa/registry/common/model/constants/ValueConstants.java
  server/server/integration/src/main/resources/sql/h2/create_table.sql
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/resource/MetaCenterResource.java
  server/server/meta/src/test/java/com/alipay/sofa/registry/server/meta/resource/MetaCenterResourceTest.java
  server/server/meta/src/test/resources/sql/h2/create_table.sql
  server/server/session/src/main/java/com/alipay/sofa/registry/server/session/bootstrap/SessionServerConfiguration.java
  server/server/session/src/main/java/com/alipay/sofa/registry/server/session/providedata/AppRevisionWriteSwitchService.java
  server/server/session/src/test/java/com/alipay/sofa/registry/server/session/providedata/AppRevisionWriteSwitchServiceTest.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/convertor/AppRevisionDomainConvertor.java
  server/store/jdbc/src/main/java/com/alipay/sofa/registry/jdbc/domain/AppRevisionDomain.java
  server/store/jdbc/src/main/resources/h2-mapper/app_revision.xml
  server/store/jdbc/src/main/resources/mapper/app_revision.xml
  server/store/jdbc/src/main/resources/sql/h2/create_table.sql
  server/store/jdbc/src/test/java/com/alipay/sofa/registry/jdbc/convertor/AppRevisionDomainConvertorTest.java
  test/src/main/resources/sql/h2/create_table.sql
Labels: cla:yes, size/L

#260 release 6.1.6
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/distribution/all/pom.xml
  server/distribution/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/pom.xml
  server/server/session/pom.xml
  server/server/shared/pom.xml
  server/store/api/pom.xml
  server/store/jdbc/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: cla:yes, size/M

#261 fix: typo dataValue
  client/impl/src/main/resources/com/alipay/sofa/registry/client/log/log4j/log-conf.xml
  client/impl/src/main/resources/com/alipay/sofa/registry/client/log/logback/log-conf.xml
Labels: bug, cla:yes, size/M

#262 Release 617 dev
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/distribution/all/pom.xml
  server/distribution/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/pom.xml
  server/server/session/pom.xml
  server/server/shared/pom.xml
  server/store/api/pom.xml
  server/store/jdbc/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: cla:yes, size/M
