Repository sofastack/sofa-registry, pull requests merged in 2023-02, with the labels that each got.

#276 Release 619
  VERSION
  client/all/pom.xml
  client/api/pom.xml
  client/impl/pom.xml
  client/log/pom.xml
  client/pom.xml
  core/pom.xml
  pom.xml
  server/common/model/pom.xml
  server/common/pom.xml
  server/common/util/pom.xml
  server/distribution/all/pom.xml
  server/distribution/pom.xml
  server/pom.xml
  server/remoting/api/pom.xml
  server/remoting/bolt/pom.xml
  server/remoting/http/pom.xml
  server/remoting/pom.xml
  server/server/data/pom.xml
  server/server/integration/pom.xml
  server/server/meta/pom.xml
  server/server/meta/src/main/java/com/alipay/sofa/registry/server/meta/cleaner/AppRevisionCleaner.java
  server/server/meta/src/test/java/com/alipay/sofa/registry/server/meta/cleaner/AppRevisionCleanerTest.java
  server/server/pom.xml
  server/server/session/pom.xml
  server/server/shared/pom.xml
  server/store/api/pom.xml
  server/store/jdbc/pom.xml
  server/store/jraft/pom.xml
  server/store/pom.xml
  test/pom.xml
Labels: cla:no, First-time contributor, size/L

#290 increase remoteSyncSlotLeaderExecutorQueueSize and remoteSyncSlotLead…
  server/server/data/src/main/java/com/alipay/sofa/registry/server/data/bootstrap/MultiClusterDataServerConfigBean.java
Labels: cla:yes, size/XS

#295 fix integration test execute twice
  test/pom.xml
Labels: bug, cla:yes, size/S
